version: "3.8"
services:
    db:
        image: mysql:latest
        container_name: mySqlCont
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: testdb
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - my-db:/var/lib/mysql
    cache:
        image: redis:6.2-alpine
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes:
            - cache:/data
    api:
        container_name: urlShortener
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - NODE_ENV=development
        image: urlshortener
        depends_on:
            - db
            - cache
        ports:
            - 3000:3000
        environment:
            NODE_ENV: production
            DB_HOST: db
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: root
            DB_NAME: testdb
            REDIS_HOST: cache
            REDIS_PORT: 6379
            REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        links:
            - db
            - cache
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
volumes:
    my-db:
    cache:
    api:
